[build]
	command = "npm run install-functions-dep"
	functions = "functions"
	publish = "src"

[dev]
	functions = "functions"
	publish = "src"

[[redirects]]
	from = "/"
	to = "/search.html"
	status = 200
	force = true